--1. What is the total number of rows in each of the 3 tables in the database? 

SELECT * 
FROM Customer
--------------------
SELECT * 
FROM prod_cat_info
--------------------
SELECT * 
FROM Transactions

--2. What is the total number of transactions that have a return? 
SELECT * 
FROM Transactions
WHERE total_amt <0;

--3. As you would have noticed, the dates provided across the datasets are not in a correct format. 
--As first steps, pls convert the date variables into valid date formats before proceeding ahead.

UPDATE Transactions
SET tran_date = CONVERT(DATE,tran_date,105)

--4. What is the time range of the transaction data available for analysis? 
--Show the output in number of days, months and years simultaneously in different columns.

SELECT *,DATEDIFF(DAY,OLD,RECENT) Dayss,
DATEDIFF(MONTH,OLD,RECENT) Months,
DATEDIFF(YEAR,OLD,RECENT) Years
FROM
	(SELECT MAX(tran_date) RECENT,
	MIN(tran_date) OLD
	FROM Transactions)X

--5. Which product category does the sub-category “DIY” belong to? 

SELECT * 
FROM prod_cat_info
WHERE prod_subcat = 'DIY';

--1. Which channel is most frequently used for transactions? 

SELECT TOP 1 
Store_type,
COUNT(Store_type) No_Of_Orders
FROM Transactions
GROUP BY Store_type
ORDER BY No_Of_Orders DESC;

--2. What is the count of Male and Female customers in the database? 

SELECT Gender,
COUNT(*) AS No_Of_Employee
FROM Customer
GROUP BY Gender
----------------------------------------
SELECT * 
FROM Customer
WHERE Gender  IS NULL


--3. From which city do we have the maximum number of customers and how many? 
 
SELECT TOP 1
city_code,
COUNT(*) AS Customer
FROM Customer
GROUP BY city_code
ORDER BY Customer  DESC

--4. How many sub-categories are there under the Books category? 

SELECT prod_cat,
COUNT(prod_subcat) AS NO_OF_SUBCATE
FROM prod_cat_info
WHERE prod_cat = 'Books'
GROUP BY prod_cat

--5. What is the maximum quantity of products ever ordered? 

SELECT prod_cat_code,
MAX(Qty)
FROM Transactions
WHERE QTY > 0
GROUP BY prod_cat_code

--6. What is the net total revenue generated in categories Electronics and Books? 

SELECT prod_cat,
ROUND(SUM(total_amt),2) AS TOTAL_SALE
FROM Transactions T
LEFT JOIN prod_cat_info P
ON T.prod_cat_code = P.prod_cat_code AND
T.prod_subcat_code = P.prod_sub_cat_code
WHERE total_amt > 0 AND
prod_cat IN ('Electronics','Books')
GROUP BY prod_cat

--7. How many customers have >10 transactions with us, excluding returns? 

SELECT cust_id,
COUNT(cust_id) NO_OF_ORDERS
FROM Transactions
WHERE total_amt > 0
GROUP BY cust_id
HAVING COUNT(cust_id) > 10
ORDER BY NO_OF_ORDERS DESC

--8. What is the combined revenue earned from the “Electronics” & “Clothing” categories, from “Flagship stores”.

SELECT ROUND(SUM(total_amt),2) AS SALE_BY_Electronics_Clothing
FROM Transactions
WHERE prod_cat_code IN (1,3) AND 
total_amt >0 AND 
Store_type = 'Flagship store'

--9. What is the total revenue generated from “Male” customers in “Electronics” category?
--Output should display total revenue by prod sub-cat.

SELECT T.prod_subcat_code ,
ROUND(SUM(total_amt),2)  AS REVENUE
FROM Transactions T
LEFT JOIN Customer C
ON T.cust_id = C.customer_Id
WHERE C.Gender = 'M' AND 
prod_cat_code = 3
GROUP BY T.prod_subcat_code
ORDER BY REVENUE DESC

--10.What is percentage of sales and returns by product sub category; display only top 5 sub categories in terms of sales?

with sales_data as(
	select prod_subcat_code,
	sum(case when Qty< 0 then total_amt  else 0 end  ) as return_sale,
	sum(case when qty > 0  then total_amt else 0 end) as sale
	from Transactions
	group by prod_subcat_code	

)	    
select top 5 
  prod_subcat_code,
    Sale,
    Return_Sale,
	ROUND(sale * 100 / SUM(SALE) OVER(),2) Sales_Percentage,
	ROUND(return_sale * 100 / SUM(return_sale) OVER(),2) Sales_Percentage
from sales_data
order by sale desc



--11. For all customers aged between 25 to 35 years find what is the net total revenue 
--generated by these consumers in last 30 days of transactions from max transaction 
--date available in the data?

;WITH max_date AS (
    SELECT MAX( tran_date) AS MAXX
    FROM Transactions
)

SELECT 
    ROUND(SUM(T.total_amt),2) AS Net_Revenue
FROM Customer C
JOIN Transactions T
    ON C.customer_Id = T.cust_id
CROSS JOIN max_date M
WHERE T.Qty > 0
AND DATEDIFF(YEAR, C.DOB, M.MAXX) BETWEEN 25 AND 35
AND t.tran_date 
    BETWEEN DATEADD(DAY,-30,M.MAXX) AND M.MAXX;

   
--12.Which product category has seen the max value of returns in the last 3 months of 
--transactions?
WITH max_date AS (
    SELECT MAX(tran_date) AS maxx
    FROM Transactions
)

SELECT 
    prod_cat_code,
    SUM(CASE 
            WHEN qty < 0 THEN qty 
            ELSE 0 
        END) AS total_return
FROM Transactions t
CROSS JOIN max_date m
WHERE t.tran_date BETWEEN DATEADD(MONTH, -3, m.maxx) AND m.maxx
GROUP BY prod_cat_code
ORDER BY TOTAL_RETURN ;


--13.Which store-type sells the maximum products; by value of sales amount and by quantity sold? 
   
SELECT TOP 1
    Store_type,
    SUM(CASE  WHEN total_amt > 0 THEN   total_amt ELSE 0 END) Sale ,
    SUM(CASE WHEN Qty > 0 THEN Qty ELSE 0 END) Sold_QTY
FROM Transactions
GROUP BY Store_type
ORDER BY SALE DESC, SOLD_QTY   DESC


--14.What are the categories for which average revenue is above the overall average. 
with avgg as (
    select 
        AVG(case when total_amt > 0 then total_amt else 0 end ) as average
    from Transactions 

)
select 
    prod_cat_code,
    avg(case when total_amt > 0 then total_amt else 0 end) cat_avg
from Transactions
cross join avgg 
group by prod_cat_code , average
having avg(case when total_amt > 0 then total_amt else 0 end) > average



--15. Find the average and total revenue by each subcategory for the categories which 
--are among top 5 categories in terms of quantity sold.
with top_5_cate  as (
        select top 5
                prod_cat_code,
                sum(case when Qty  >0 then Qty else 0 end ) as qty_sol
        from Transactions
        group by prod_cat_code
        order by qty_sol desc
)
select t.prod_cat_code,
t.prod_subcat_code,
        round(avg(case when total_amt > 0 then total_amt else 0 end ),2) as sales,
        round(sum(case when total_amt > 0 then total_amt else 0 end ),2) as sales

from Transactions t
left join top_5_cate c
on c. prod_cat_code  = t.prod_cat_code
where t.prod_cat_code in (select prod_cat_code from top_5_cate)
group by t.prod_cat_code,t.prod_subcat_code
order by  t.prod_cat_code asc
